### ISSUE TITLE
Scrolling jumps if you scroll from the end of the page

### ISSUE THREAD

**Issue by Defman21** [Komodo/komodo-website#17]
I'm talking about this page: http://komodoide.com/pricing/
Also I recorded a video with the bug: http://youtu.be/USZk9146YQQ
This happens only on this page.

**Comment by Defman21** [comment]
Also Google conversion frame take 13px height so the footer is not in the bottom of browser window.

**Comment by Naatan** [comment]
Fixed https://github.com/Komodo/komodo-website/commit/fdd6e80706ba9debe7578437efcd8ae739fb5cb1

Thanks

**Comment by Defman21** [comment]
Scrolling not fixed. But it's not so important.
