### ISSUE TITLE
Make the Download button red if the latest release is pre-release [package page]

### ISSUE THREAD

**Issue by Defman21** [Komodo/komodo-website#31]
Just to warn that it's a pre-release and it can work not as expected, I think it would be better to warn the user that he will be using a pre-release version which is not prepare to general use or something like that by making the Download button red (instead of blue, red - bad, blue - good :sunglasses: )

**Comment by cgchoffman** [comment]
I don't really see why this is necessary.  It says pre-release in 3 different places on the screen, you have to explicitly navigate to the **pre-release** page from the default **try** page and it says it's a beta.  We don't want to make people hesitant to downloading.  We want people as many people as possible using this build.

**Comment by Defman21** [comment]
I'm talking about Packages/Resources page... huh. Sorry for confusing :stuck_out_tongue:

**Comment by cgchoffman** [comment]
yes, mentioning what page you're talking about, that would be helpful :)
