### ISSUE TITLE
System Requirements doesn't fit popup

### ISSUE THREAD

**Issue by babobski** [Komodo/komodo-website#42]
popup doesnt fit System Requirements (winodws 10 FF):
![snap 2015-10-30 at 18 26 59](https://cloud.githubusercontent.com/assets/3530262/10852978/0793d126-7f34-11e5-905c-309ec7741a3c.png)

**Comment by cgchoffman** [comment]
If you make your window really short you can repro on Chrome too.  maybe we can just show the "guessed platform" requirements?  Or just allow it to over flow over the footer, which seems to be blocking it some how.

**Comment by babobski** [comment]
Is gone ;)
