### ISSUE TITLE
generated link for download source not working (404)

### ISSUE THREAD

**Issue by babobski** [Komodo/komodo-website#43]
Had a new [issue](https://github.com/babobski/komodo-bootstrap-snippets/issues/1) on my bootstrap snippet, the download link on komodo ide is not working. It takes you to a 404 page.
Tetsed it also with my sass compiler but here the link for dowloading source is not working either.

**Comment by cgchoffman** [comment]
Thanks @babobski.  I'm not sure whats going on but your toolbox.yml entry looks fine
https://github.com/Komodo/Packages/blob/master/toolbox.yml

@Naatan will have a look.

**Comment by babobski** [comment]
Is working now, so I'm closing this one
