### ISSUE TITLE
forum on komodoide.com down

### ISSUE THREAD

**Issue by babobski** [Komodo/komodo-website#44]
Currently the forum is down, when i click on the form link it takes me to a 404.
![snap 2015-11-22 at 17 44 44](https://cloud.githubusercontent.com/assets/3530262/11324956/c06a23f8-9140-11e5-9d00-6fbfbb3c1e15.png)

**Comment by Defman21** [comment]
I've reported about it in the IRC channel, but it's Sunday and everyone are on their vacation :)

**Comment by babobski** [comment]
Yeah, im also enjoying my weekend, but i tought just report it if maybe no one else noticed it. 
btw what is the IRC channel?

**Comment by Defman21** [comment]
#komodo on irc.mozilla.org

**Comment by babobski** [comment]
ah oke, still learning every day something new. But if you already reported it, im closing this one as its a duplicate :stuck_out_tongue_winking_eye:
