### ISSUE TITLE
Komodo IDE 10 folding of SUBs is broken

### ISSUE THREAD

**Issue by arnoldrb** [Komodo/komodo-website#54]
In Komodo IDE 8 (my previous version) I could fold a perl sub and thus put it conveniently out of the way. Now with Komodo IDE 10.1.2 I find that all of my subs no longer fold completely. They sort of partially fold leaving more folds and ultimately a visual mess in place of the neat single remaining sub line that I am familiar with from version 8.  Some subs do fold properly. I am not sure why this is - perhaps thay are just shorter.
Is there some way to adjust the 'level' (?) of the folds so that sub-folds within a subroutine will fold properly?
I do like the new capability to be able to fold long comments. Very useful in tidying up.
Thanks,
Ray

**Comment by mitchell-as** [comment]
Hi, do you have a code example that I can do a visual check with? We did upgrade our Perl lexer recently to handle more Perl better, but the folding methods may have changed in the process.

**Comment by mitchell-as** [comment]
Oh, please file this ticket on https://github.com/Komodo/KomodoEdit/issues, not this project.
